### ISSUE TITLE
启动HomeBridge成功，能操作网关灯等，几秒后提示密码无效不能操作

### ISSUE THREAD

**Issue by geminishao** [YinHangCode/homebridge-mi-aqara#102]
DEBUG LOG
17-11-15 01:35:03] [MiAqaraPlatform] [DEBUG][Send]{"cmd":"write","model":"gateway","sid":"7811dca47e17","data":"{\"rgb\":1694498815, \"key\": \"7ea801dcdf53e637fb4ffb3be1528f19\"}"}
[2017-11-15 01:35:03] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"write_ack","model":"gateway","sid":"7811dca47e17","short_id":0,"data":"{\"rgb\":1694498815,\"illumination\":1292,\"proto_version\":\"1.0.9\"}"}
[2017-11-15 01:35:04] [MiAqaraPlatform] [DEBUG][Send]{"cmd":"write","model":"gateway","sid":"7811dca47e17","data":"{\"rgb\":0, \"key\": \"7ea801dcdf53e637fb4ffb3be1528f19\"}"}
[2017-11-15 01:35:04] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"write_ack","sid":"7811dca47e17","data":"{\"error\":\"Invalid key\"}"}
[2017-11-15 01:35:04] [MiAqaraPlatform] [ERROR]Error: Invalid key
[2017-11-15 01:35:04] [MiAqaraPlatform] [ERROR]Error: Invalid key
    at MiAqaraPlatform.parseMessage (/usr/lib/node_modules/homebridge-mi-aqara/index.js:300:26)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage [as onmessage] (dgram.js:544:8)

**Comment by YinHangCode** [comment]
就是密码不对，确认密码。

**Comment by geminishao** [comment]
@YinHangCode
换过好几次的都确认过密码了，大写还是小写也都试过了，依旧报错，密码不对为什么刚启动的几秒能成功控制

**Comment by YinHangCode** [comment]
[2017-11-15 01:35:04] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"write_ack","sid":"7811dca47e17","data":"{"error":"Invalid key"}"}

这句是网关那边返回来的原始信息。。。。
密码要保持原样，是大写就大写 是小写就小写

**Comment by geminishao** [comment]
@YinHangCode
之前是IOS的大写密码，刚才用安卓手机刷了小写密码试了，依旧是在对灯成功操作几次后，又报了密码无效，难道这密码有使用次数限制？
会不会是硬件问题，打算退货了

**Comment by fxdpz** [comment]
use 0.5.3 

npm install --global homebridge-mi-aqara@0.5.3

**Comment by liyoungc** [comment]
@geminishao 我遇到一樣的問題， 一開始可以控制，大約20秒後就顯示invalid key
如果把key故意寫錯，則從一開始就不能控制
我原本是在離ap比較遠的書房的iMac設定，後來換另一個Macbook air，到離ap近一點的客廳設定，就一切正常了。我把air拿到書房，結果也怪怪的不能跑，但不是invalid key。所以我無法判斷是不同電腦還是訊號不好的關係。建議你兩個都試試!

**Comment by 18601673063** [comment]
wireless LAN issues!

**Comment by HelloMorningStar** [comment]
以上问题有了解决方案，与作者的插件无关，主要问题来自网络和LINUX。但我还是建议作者局域网内部采用token比较稳定，作者其它采用token的插件均无此类问题。
### 运行环境：
A, ubuntu：1）linux deploy Ubuntu14.04；2）电脑（非虚拟机）ubuntu18.04均爆出错误[MiAqaraPlatform] [ERROR]Error: Invalid key或类似的问题。
B, win10下安装homebridge，用此插件一切正常。
所以没事不要倒腾LINUX!!!

### 问题解决：
### 1， “嗅探”功能关闭：我的环境有4台路由器，2台交换机，全部配置在一个局域网段内（不要因为win10下运行正常而不去排除网络问题），把路由器内部的“嗅探”功能关闭；
2，将ubuntu的网卡的

>  promisc
打开，打开...你会看到网卡状态栏有“UP BROADCAST RUNNING **PROMISC** MULTICAST  MTU:1500  Metric:1”

同时在android手机和ubuntu电脑上运行homebridge测试，一切正常。

补充：ubuntu电脑重新启动后网卡PROMISC会自动关闭（我之前电脑出现问题可能还与指定了静态IP有关系），手机上的LINUX DEPLOY运行UBUNTU不会自动关闭PROMISC。但是仍然一切正常。

**Comment by ksotin** [comment]
试试把路由器和网关移远一点

**Comment by MadSummer** [comment]
see this : https://github.com/YinHangCode/homebridge-mi-aqara/issues/219#issuecomment-543874024
