### ISSUE TITLE
运行一段时间后会出现timeout错误

### ISSUE THREAD

**Issue by linxingyulxy** [YinHangCode/homebridge-mi-aqara#106]
`[2017-11-21 11:38:08] [MiAqaraPlatform] [ERROR]Error: timeout: {"cmd":"write","model":"switch","sid":"158d0000e64bac","data":"{\"status\":\"click\", \"key\": \"40d12e51180d1a69ff659ac6ce2bd240\"}"}
[2017-11-21 11:38:08] [MiAqaraPlatform] [ERROR]Error: timeout: {"cmd":"write","model":"switch","sid":"158d0000e64bac","data":"{\"status\":\"click\", \"key\": \"40d12e51180d1a69ff659ac6ce2bd240\"}"}
    at Timeout.setInterval (/usr/lib/node_modules/homebridge-mi-aqara/index.js:407:27)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)`
重启后就会恢复正常，这个是路由器不稳定吗？
还有打开 homekit的时候，网关都要未响应一会

**Comment by lxy1992** [comment]
我遇到了同样的问题，重启后也未有改变

**Comment by lxy1992** [comment]
主要是网管灯，智能插座，一直出现没有响应的情况。

**Comment by sunjunlishi** [comment]
same  to  you
