### ISSUE TITLE
Issue with UUID during start

### ISSUE THREAD

**Issue by kdamsk** [YinHangCode/homebridge-mi-aqara#11]
Can't start homebridge. Previously had homebridge-aqara plugin(now uninstalled)
Error is: 
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

Full log:
[2017-6-23 16:25:42] Aqara server is listening on port 9898.
[2017-6-23 16:25:42] Homebridge is running on port 51826.
[2017-6-23 16:25:42] add Gateway 34ce0088d997
[2017-6-23 16:25:42] add Device 34ce0088d997
[2017-6-23 16:25:42] add Device 158d0001a35aea
[2017-6-23 16:25:42] add Device 158d00011501aa
[2017-6-23 16:25:42] add Device 158d000123045d
[2017-6-23 16:25:42] add Device 158d00012317e9
[2017-6-23 16:25:42] add Device 158d000163e302
[2017-6-23 16:25:42] add Device 158d00016c409f
[2017-6-23 16:25:42] add Device 158d0001231fe2
[2017-6-23 16:25:42] add Device 158d00012403ae
[2017-6-23 16:25:42] {"cmd":"read_ack","model":"gateway","sid":"34ce0088d997","short_id":0,"data":"{\"rgb\":0,\"illumination\":1292,\"proto_version\":\"1.0.7\"}"}
[2017-6-23 16:25:42] create new accessories - UUID: 5a72a562-a57b-4c1c-8897-b3fede914fc9, type: Light Sensor, deviceSid: 34ce0088d997
[2017-6-23 16:25:42] create new accessories - UUID: 147c936f-7701-494d-93cd-d469a85e1fe2, type: Gateway Light, deviceSid: 34ce0088d997
[2017-6-23 16:25:42] {"cmd":"read_ack","model":"cube","sid":"158d00011501aa","short_id":7941,"data":"{\"voltage\":3015}"}
[2017-6-23 16:25:42] create new accessories - UUID: 20e0bf36-e508-48bf-90cb-20a74fc3e73a, type: Magic Square Flip90, deviceSid: 158d00011501aa
[2017-6-23 16:25:42] create new accessories - UUID: 1b8a34e5-46bf-46bb-9207-d52f3e783877, type: Magic Square Flip180, deviceSid: 158d00011501aa
[2017-6-23 16:25:42] create new accessories - UUID: 6bb85f88-8835-4234-b5ca-6489f95d1e1a, type: Magic Square Move, deviceSid: 158d00011501aa
[2017-6-23 16:25:42] create new accessories - UUID: 74c25e7a-63c8-48f7-8f89-ac4761a52150, type: Magic Square Tap Twice, deviceSid: 158d00011501aa
[2017-6-23 16:25:42] create new accessories - UUID: aabff341-fdc7-424d-896d-24ad5b04d3f8, type: Magic Square Shake Air, deviceSid: 158d00011501aa
[2017-6-23 16:25:42] create new accessories - UUID: fcbb5cdd-43e1-4a67-b5f6-164e73c2a90d, type: Magic Square Rotate, deviceSid: 158d00011501aa
[2017-6-23 16:25:42] {"cmd":"read_ack","model":"motion","sid":"158d000123045d","short_id":24015,"data":"{\"voltage\":3045,\"status\":\"no_motion\"}"}
[2017-6-23 16:25:42] create new accessories - UUID: 0fa0de55-1a7b-4623-9eaa-73ba0926b12a, type: Motion Sensor, deviceSid: 158d000123045d
[2017-6-23 16:25:42] {"cmd":"read_ack","model":"motion","sid":"158d00012317e9","short_id":47994,"data":"{\"voltage\":3075,\"status\":\"no_motion\"}"}
[2017-6-23 16:25:42] create new accessories - UUID: 25c7042b-68ee-4e30-988f-495b35e30aa4, type: Motion Sensor, deviceSid: 158d00012317e9
[2017-6-23 16:25:42] {"cmd":"read_ack","model":"motion","sid":"158d000163e302","short_id":29045,"data":"{\"voltage\":3045,\"status\":\"motion\"}"}
[2017-6-23 16:25:42] create new accessories - UUID: 8b27ac0d-2031-4864-a39d-abde3643397d, type: Motion Sensor, deviceSid: 158d000163e302
[2017-6-23 16:25:42] {"cmd":"read_ack","model":"motion","sid":"158d0001231fe2","short_id":45324,"data":"{\"voltage\":3065,\"status\":\"no_motion\"}"}
[2017-6-23 16:25:42] create new accessories - UUID: d0110c17-f69b-4c14-8d8a-f70887253ddd, type: Motion Sensor, deviceSid: 158d0001231fe2
[2017-6-23 16:25:42] {"cmd":"read_ack","model":"switch","sid":"158d00012403ae","short_id":13649,"data":"{\"voltage\":3115}"}
[2017-6-23 16:25:42] create new accessories - UUID: 46be1e9e-4fdd-4b5f-a955-b2877257dadb, type: Button, deviceSid: 158d00012403ae
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:228
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 0fa0de55-1a7b-4623-9eaa-73ba0926b12a
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:228:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:274:10)
    at Server._handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:437:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:36:10)
    at emitOne (events.js:96:13)
    at API.emit (events.js:188:7)
    at API.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:159:8)
    at MiAqaraPlatform.parseMessage (/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:351:22)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)

**Comment by YinHangCode** [comment]
cd ~/.homebridge/accessories
rm cachedAccessories
nano cachedAccessories
enter "[]"(exclude double quotes) and ctrl+o save, ctrl+x exit.
execute homebridge -D

**Comment by kdamsk** [comment]
working! thx
