### ISSUE TITLE
Home app中找不到homebridge

### ISSUE THREAD

**Issue by zhuqichen0310** [YinHangCode/homebridge-mi-aqara#126]
你好 打扰  网上找的教程  群晖中docker安装homebridge 使用小米二代网关
输入8位代码找不到设备
docker 终端里面查看到：
events.js:136                                                                          
      throw er; // Unhandled 'error' event                                             
      ^                                                                                
                                                                                       
Error: listen EADDRINUSE :::53699                                                      
    at Object._errnoException (util.js:1031:13)                                        
    at _exceptionWithHostPort (util.js:1052:20)                                        
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)                         
    at listenInCluster (net.js:1408:12)                                                
    at Server.listen (net.js:1496:7)                                                   
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/ha
p-nodejs/lib/util/eventedhttp.js:60:19)                                                
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs
/lib/HAPServer.js:158:20)                                                              
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/ha
p-nodejs/lib/Accessory.js:601:16)                                                      
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:126:16)   
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:96:10)   

请问什么意思

**Comment by YinHangCode** [comment]
http://wiki.yinhh.com/Wiki.jsp?page=HomeBridge#section-HomeBridge-_E5_B8_B8_E8_A7_81_E9_97_AE_E9_A2_98

**Comment by zhuqichen0310** [comment]
你好 这是结果 就运行了一个homebridge啊 关闭进程之后docker容器也就关掉了 这个占用网关的报错信息在pin的码下面 
[config.txt](https://github.com/YinHangCode/homebridge-mi-aqara/files/1608500/config.txt)


# ps -eaf|grep homebridge|grep -v grep                                                 
avahi       48     1  0 05:23 ?        00:00:00 avahi-daemon: registering [marcoraddatz
-homebridge1-33.local]                                                                 
root        50     1  0 05:23 console  00:00:00 homebridge

**Comment by YinHangCode** [comment]
kill -9 50

**Comment by zhuqichen0310** [comment]
kill 之后就变这样了 ![snipaste_2018-01-08_21-29-46](https://user-images.githubusercontent.com/13390086/34672872-18903e84-f4bb-11e7-8d36-a0085d840a6e.jpg)

**Comment by YinHangCode** [comment]
现在再启动homebridge呢？

**Comment by zhuqichen0310** [comment]
重启之后 依旧显示占用 我怀疑是路由器的firewall 配置问题

**Comment by YinHangCode** [comment]
这个错误就是端口被占用了。。。 是不是启动了好几份homebridge？
