### ISSUE TITLE
小米网关小夜灯 开关、亮度和颜色操作，闪退 问题 

### ISSUE THREAD

**Issue by Genng** [YinHangCode/homebridge-mi-aqara#17]
`{"id":-1,"method":"get_prop","params":["power"]}
{"id":1,"method":"set_power","params":["off","smooth",500]}
crypto.js:191
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

TypeError: Key must be a buffer
    at TypeError (native)
    at new Cipheriv (crypto.js:191:16)
    at Object.Cipheriv (crypto.js:189:12)
    at MiAqaraPlatform.getWriteKeyByDeviceSid (/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:252:25)
    at GatewayParser.controlLight (/usr/local/lib/node_modules/homebridge-mi-aqara/DeviceParsers/GatewayParser.js:166:29)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-aqara/DeviceParsers/GatewayParser.js:109:22)
    at emitMany (events.js:127:13)
    at Characteristic.emit (events.js:201:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:756:22)`

**Comment by YinHangCode** [comment]
局域网通信密码确认是否正确 区分大小写

**Comment by Genng** [comment]
@YinHangCode  应该是对的，网关下的子设备正常，并且小夜灯的亮度和显示状态正常，就是修改亮度或者开关的时候，报错

**Comment by Genng** [comment]
@YinHangCode  我把homebridge-miio 下 miio的文件，替换成了miio里面的.. 参考http://weibo.com/ttarticle/p/show?id=2309404122611511603071  是否是这个问题？

**Comment by YinHangCode** [comment]
读取数据不需要那个key，更改的时候才需要。参考下[https://github.com/YinHangCode/homebridge-mi-aqara/issues/7](https://github.com/YinHangCode/homebridge-mi-aqara/issues/7)

**Comment by Genng** [comment]
@YinHangCode  
是设备sid大小写问题，
MiAqaraPlatform .js中gatewayPasswords取得配置文件config.json设备号是大写的key，
网关的GatewayParser.js获取的设备号是小写的，
没匹配上。

可以修改config.json的sid为小写字母
或者
` this.gatewayPasswords = password.reduce(function (gatewayPasswords, password, index) {
        gatewayPasswords[sid[index].toLowerCase()] = password;
        that.log("Load password from config.json file"+sid[index].toLowerCase()+"--"+password);
        return gatewayPasswords;
    }, {});`
gatewayPasswords获取密码的时候，转成小写
`sid[index].toLowerCase()`

**Comment by YinHangCode** [comment]
@Genng 
![image](https://user-images.githubusercontent.com/15974677/28257172-444a8f38-6afb-11e7-8e4d-bf79a879b0dc.png)
这段话我是从官方的那个介绍里copy过来的，绿米的局域网通信协议用的都是小写，所以是需要改成小写的。
