### ISSUE TITLE
No accessories found.

### ISSUE THREAD

**Issue by eliac7** [YinHangCode/homebridge-mi-aqara#188]
```
[MiAqaraPlatform] Initializing MiAqaraPlatform platform...
[2018-6-2 12:37:55] [MiAqaraPlatform] [INFO]**************************************************************
[2018-6-2 12:37:55] [MiAqaraPlatform] [INFO]           MiAqaraPlatform v0.6.8 By YinHang
[2018-6-2 12:37:55] [MiAqaraPlatform] [INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-aqara  
[2018-6-2 12:37:55] [MiAqaraPlatform] [INFO]                                         QQ Group: 107927710  
[2018-6-2 12:37:55] [MiAqaraPlatform] [INFO]**************************************************************
[2018-6-2 12:37:55] [MiAqaraPlatform] [INFO]start success...
[2018-6-2 12:37:55] [MiAqaraPlatform] [INFO]config gateways: c4a36648b862
[2018-6-2 12:37:55] [MiAqaraPlatform] [INFO]binding to the default interface
[2018-6-2 12:37:55] Loading 0 accessories...

```
It can successfully find the gateway, but it can't find any of the accessories. I copied pasted the list of OP with all the accessories but unfortunately doesn't see any. Any ideas?

**Comment by theo-69** [comment]
Having the same Problem with one of my gateways after I updated it to newest Firmware. Did you find a solution?

**Comment by theo-69** [comment]
Any solution?

**Comment by eliac7** [comment]
Have the same firmware but still not found any solutions. If you find anything, please let me know

**Comment by theo-69** [comment]
Really strange behavior, Gateway however is still responding to https://github.com/YinHangCode/homebridge-mi-gateway-security from same author, however its via token not Mac adress.

**Comment by Menghongli** [comment]
@eliac7 would you mind post your `config.json` here as well?

**Comment by theo-69** [comment]
thats the strange thing, I removed all except the standard config and its still behaving like that. `Loading 0 Accessories...`

**Comment by trlsmax** [comment]
same happen here 
my config.json is :

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:CC:CC:CC:CE:CC",
        "port": 51826,
        "pin": "031-45-aaa"
    },

    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
	{
		"accessory":"DummySwitch",
		"name":"My Switch 1"
	}
    ],

    "platforms": [
	{
		"platform":"MiAqaraPlatform",
		"gateways":{
			"abcdabcdabcd":"abcdabcdabcd"
		},
		"defaultValue":{
			"7c49eb1df983":{
				"AcPartner_Switch_JoinPermission":{
					"name":"hot water"
				}
			},
			"158d0002392fa8":{
				"Global":{
					"serviceType":"Lightbulb"
				},
				"DuplexSwitch_Switch_Left":{
					"name":"yang tai light"
				},
				"DuplexSwitch_Switch_Right":{
					"name":"master bedroom light"
				}
			},
			"158d0002459bd7":{
				"Global":{
					"serviceType":"Lightbulb"
				},
				"DuplexSwitch_Switch_Left":{
					"name":"cantin light"
				},
				"DuplexSwitch_Switch_Right":{
					"name":"living room light"
				}
			}
		}
	}
    ]
}
```

when I use debug mode, I can see the switch message

```
[2018-6-12 13:54:32] [MiAqaraPlatform] [DEBUG][Send]{"cmd": "whois"}
[2018-6-12 13:54:32] [MiAqaraPlatform] [INFO]server is listening on port 9898.
[2018-6-12 13:54:32] Homebridge is running on port 51826.
[2018-6-12 13:54:32] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"iam","protocal":"UDP","port":"9898","sid":"7c49eb1df983","model":"acpartner.v3","proto_version":"2.0.1","ip":"192.168.1.44"}
[2018-6-12 13:55:51] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"report","model":"ctrl_neutral2","sid":"158d0002392fa8","params":[{"channel_1":"on"}]}
[2018-6-12 13:55:53] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"report","model":"ctrl_neutral2","sid":"158d0002392fa8","params":[{"channel_1":"off"}]}
```

**Comment by theo-69** [comment]
just updated the node to 10.4.0, check your `node -v` Now its working

**Comment by trlsmax** [comment]
@theo-69 I use the homebridge docker image with the node version 8.11.2, I will try to upgrade it, thanks.

@Menghongli of course I use the correct MAC in lower cases and password in upper cases. But it did not work. I will upgrade node as @theo-69 suggested

**Comment by eliac7** [comment]
```
homebridge
/usr/lib/node_modules/homebridge/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/usr/lib/node_modules/homebridge/node_modules/ed25519-hap/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/usr/lib/node_modules/homebridge/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/ed25519-hap/index.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)

```

After installing 10.4.1, homebridge doesn't compile. Any ideas?

**Comment by theo-69** [comment]
try
`cd $(npm -g prefix)
npm rebuild`

**Comment by eliac7** [comment]
Unfortunately, it doesn't work. Any way to make it happen or do I have to uninstall completely Homebridge? If yes, how could I do it?

**Comment by theo-69** [comment]
try to remove and than reinstall the plugin

**Comment by lopify** [comment]
I had the same problem for few days, then I realised I was using the wrong Mac address of the gateway, now working perfectly

**Comment by eliac7** [comment]
Do I have to enter the accessories manually or it detects them automatically?

**Comment by theo-69** [comment]
It will detect them automatically.

**Comment by eliac7** [comment]
Thanks for the response. I managed to make them work but I am facing an issue.
It appears that error:
[https://i.imgur.com/dARJDou.jpg](url)

Any idea whaty I am doing wrong?

**Comment by theo-69** [comment]
Great congrats. What was the problem? After that you can please close this issue.

**Comment by eliac7** [comment]
I really don't know. I just changed several times the password and finally it worked.
