### ISSUE TITLE
Problem issue and feedback

### ISSUE THREAD

**Issue by sokompheak** [YinHangCode/homebridge-mi-aqara#19]
1. Gateway: there is 2 accessories from gateway is light color and light level. 

- Light color and brightness not response.
- light level can not modify

2. Power Plug: not response.

3. wireless switch just appear in home app. but there is not usable.

4. Door Sensor is worked.

5. Motion Sensor is worked too.

whenever I click on Gateway light or Power plug to turn on. Homebridge will shutdown.
![screen shot 2017-07-03 at 19 06 57](https://user-images.githubusercontent.com/29452834/27792213-e037e3d4-6022-11e7-81eb-ad2b6aeb75de.png)

**Comment by sokompheak** [comment]
Update... I got it fixed. I confuse to use Mac address in Mi Home about. Btw, I can't find the way to add power strip.

**Comment by a900927** [comment]
@sokompheak hey guy,just see ur config.json file,the mi-aqara password is using uppercase letters?if not,fix it.the password must be  uppercase letters.

**Comment by sokompheak** [comment]
I think it is not about Password uppercase. The problem is Mac address. I put wrong MAC address. now it is working fine. but the feature of gateway in homebridge has limit. Why has no Gateway Security? like arm and disarm when i'm home or when i leave home.

**Comment by sokompheak** [comment]
I also found and Install [Miio](https://github.com/Bluebie/homebridge-miio) for Power Strip.

**Comment by sokompheak** [comment]
beside if you Uppercase the passwords, all accessories will not response.

**Comment by a900927** [comment]
@sokompheak you can use the domoticz.the gateway all feature enable

**Comment by sokompheak** [comment]
@a900927 I have never heard of it. Could you give me more info about Domoticz? 

Thank you.

**Comment by sokompheak** [comment]
Hello @a900927 i try to install it but i got error... could you help me?

**Comment by jasonsmy** [comment]
Hi, I'd like to follow up on this issue.

I too am seeing that error whenever I try to click on a "switch" type accessory.

My passwords are all in uppercase, my gateway MAC addresses correspond correctly (triple checked).

I'm getting this error:

crypto.js:194
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

TypeError: Key must be a buffer
    at TypeError (native)
    at new Cipheriv (crypto.js:194:16)
    at Object.Cipheriv (crypto.js:192:12)
    at MiAqaraPlatform.getWriteKeyByDeviceSid (/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:270:25)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-aqara/DeviceParsers/DuplexSwitchParser.js:134:37)
    at emitMany (events.js:127:13)
    at Characteristic.emit (events.js:201:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:290:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:812:22)
    at Array.forEach (native)
