### ISSUE TITLE
Add support for sensor_cube.aqgl01

### ISSUE THREAD

**Issue by lopify** [YinHangCode/homebridge-mi-aqara#190]

**Comment by Wormaap** [comment]
Same trouble here with the Cube. The Mi Home app shows mine as sensor_cube.aqgl01, and it doesn't appear through Homebridge. Interesting thing, though, is that my MagicSquareParser.js doesn't even have the list you added this name to.

**Comment by Wormaap** [comment]
Yesterday, I updated to 0.6.9 and the Cube didn't appear. Today, it's suddenly there.

**Comment by YinHangCode** [comment]
@Wormaap the interval of the find the new device is 30 minutes.

**Comment by Wormaap** [comment]
Ahh, that makes sense. The switches that showed up in the Home app still aren't doing much, though, but that's probably just me not having them figured out yet. Thank you! :)

**Comment by halk1982** [comment]
Same problem here. Everything works fine on MI home app. After updating to 0.6.9 cube finally appears to Homekit but actions triggered (shake, flip, etc) are not delivered to Homekit. Any ideas?

**Comment by cgeist** [comment]
Same problem here: the buttons / virtual switches are correctly discovered but not showing any reaction at all. (see also #214)

**Comment by cgeist** [comment]
Yes, some functionality was restored by the firmware update! Rotate, however, as well as all stateful switches still appear to be broken.

**Comment by meesjan** [comment]
I have installed version 0.7.1. In the release notes (of 0.7.0) is stated that the MagicSquare Rotate StatelessProgrammableSwitch should be working now. I have tested this, however the tile in the Home app does not show any movement when rotating the cube. Neither the action is performed.

So in my opinion the rotate function is still not working.

What about you guys?

In a previous release the rotate tile in the Home app was also moving when performing other actions. Ffor example: flip90, then the flip90 tile was moving but also the rotate tile.

**Comment by MaFlax** [comment]
I have a fix for rotate, the parser is faulty. I read the debug log and found this line: `{"cmd":"report","model":"sensor_cube.aqgl01","sid":"158d000230e589","short_id":57705,"data":"{\"rotate\":\"16,500\"}"}` there is no status anymore in the message. If you rotate clockwise, the number is positive. If you rotate counterclockwise the number is negative. So I changed 'status' to 'rotate' in the code. Here is my code for MagicSquareParser.js:
```javascript
class MagicSquareStatelessProgrammableSwitchRotateParser extends MagicSquareStatelessProgrammableSwitchBaseParser {
    getProgrammableSwitchEventCharacteristicValue(jsonObj, defaultValue) {
        var value = null;
        var proto_version_prefix = this.platform.getProtoVersionPrefixByProtoVersion(this.platform.getDeviceProtoVersionBySid(jsonObj['sid']));
        if(1 == proto_version_prefix) {
            value = this.getValueFrJsonObjData1(jsonObj, 'rotate');
        } else if(2 == proto_version_prefix) {
            value = this.getValueFrJsonObjData2(jsonObj, 'cube_status');
        } else {

        }
        
        if(parseFloat(value,10) > parseFloat(0)) {
            return this.Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS;
        } else {
            return defaultValue;
        }
    }
}
```

My idea: Create a new accessory parser that recognizes the rotation direction. So maybe this way:
```javascript
'MagicSquare_StatelessProgrammableSwitch_Rotate_Clockwise': MagicSquareStatelessProgrammableSwitchRotateClockwiseParser,
'MagicSquare_StatelessProgrammableSwitch_Rotate_Counterclockwise': MagicSquareStatelessProgrammableSwitchRotateCounterclockwiseParser
``` 

The new code above recognizes clockwise only.

All other switches are working properly. I haven't checked yet if hiding the switches is possible.

**Comment by meesjan** [comment]
> got same problem with rotate, too, not fixed after 0.7.1
> 
> But can't hide the switches, even I stated it in the config.
> 
> > 
> 
> {
> "platform": "MiAqaraPlatform",
> "gateways": {
> "xxx": "xxx"
> },
> "Xxxxxxxxx": {
> "MagicSquare_Switch_VirtualFlip180_d768": {
> "disable": true
> },
> "MagicSquare_Switch_VirtualShakeAir_d768": {
> "disable": true
> },
> "MagicSquare_Switch_VirtualTapTwice_d768": {
> "disable": true
> },
> "MagicSquare_Switch_VirtualMove_d768": {
> "disable": true
> },
> "MagicSquare_Switch_VirtualFlip90_d768": {
> "disable": true
> }
> }
> },

To disable them you have to the delete the "_d768". See below. This should work.
{
"platform": "MiAqaraPlatform",
"gateways": {
"xxx": "xxx"
},
"Xxxxxxxxx": {
"MagicSquare_Switch_VirtualFlip180": {
"disable": true
},
"MagicSquare_Switch_VirtualShakeAir": {
"disable": true
},
"MagicSquare_Switch_VirtualTapTwice": {
"disable": true
},
"MagicSquare_Switch_VirtualMove": {
"disable": true
},
"MagicSquare_Switch_VirtualFlip90": {
"disable": true
}
}
},

**Comment by meesjan** [comment]
> I have a fix for rotate, the parser is faulty. I read the debug log and found this line: `{"cmd":"report","model":"sensor_cube.aqgl01","sid":"158d000230e589","short_id":57705,"data":"{\"rotate\":\"16,500\"}"}` there is no status anymore in the message. If you rotate clockwise, the number is positive. If you rotate counterclockwise the number is negative. So I changed 'status' to 'rotate' in the code. Here is my code for MagicSquareParser.js:
> 
> ```js
> class MagicSquareStatelessProgrammableSwitchRotateParser extends MagicSquareStatelessProgrammableSwitchBaseParser {
>     getProgrammableSwitchEventCharacteristicValue(jsonObj, defaultValue) {
>         var value = null;
>         var proto_version_prefix = this.platform.getProtoVersionPrefixByProtoVersion(this.platform.getDeviceProtoVersionBySid(jsonObj['sid']));
>         if(1 == proto_version_prefix) {
>             value = this.getValueFrJsonObjData1(jsonObj, 'rotate');
>         } else if(2 == proto_version_prefix) {
>             value = this.getValueFrJsonObjData2(jsonObj, 'cube_status');
>         } else {
> 
>         }
>         
>         if(parseFloat(value,10) > parseFloat(0)) {
>             return this.Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS;
>         } else {
>             return defaultValue;
>         }
>     }
> }
> ```
> 
> My idea: Create a new accessory parser that recognizes the rotation direction. So maybe this way:
> 
> ```js
> 'MagicSquare_StatelessProgrammableSwitch_Rotate_Clockwise': MagicSquareStatelessProgrammableSwitchRotateClockwiseParser,
> 'MagicSquare_StatelessProgrammableSwitch_Rotate_Counterclockwise': MagicSquareStatelessProgrammableSwitchRotateCounterclockwiseParser
> ```
> 
> The new code above recognizes clockwise only.
> 
> All other switches are working properly. I haven't checked yet if hiding the switches is possible.

For me this is too technical (however I do understand what you explain). Hopefully one of the developers of this plugin can fix this. @YinHangCode ?

**Comment by caiminnl** [comment]
> Today I updated my gateway firmware to 1.4.1_157.0143 using the Mi Home App (on mainland china server) and now the cube is working fine. My plugin version is 0.6.9 and the buttons/switches are discovered in Homekit, assining actions also works. So you have to update your Gateway and the issue should be solved. Also restart your homebridge to refresh the accessories. So I guess it was a faulty gateway firmware.

Thank you so much! This solved my problem!

**Comment by meesjan** [comment]
> > Today I updated my gateway firmware to 1.4.1_157.0143 using the Mi Home App (on mainland china server) and now the cube is working fine. My plugin version is 0.6.9 and the buttons/switches are discovered in Homekit, assining actions also works. So you have to update your Gateway and the issue should be solved. Also restart your homebridge to refresh the accessories. So I guess it was a faulty gateway firmware.
> 
> Thank you so much! This solved my problem!

The rotate function is still not working. The other five movements are.

**Comment by flipmoo** [comment]
I just installed the cube. And i see the switches in homekit. But when i select one i get:

```
[2018-11-19 21:38:24] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"write_ack","model":"sensor_cube.aqgl01","sid":"158d000287911e","short_id":14394,"data":"{\"voltage\":2995}"}
[2018-11-19 21:38:24] [MiAqaraPlatform] [ERROR]SyntaxError: Unexpected token o in JSON at position 1
[2018-11-19 21:38:24] [MiAqaraPlatform] [ERROR]SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at MagicSquareSwitchVirtualFlip90Parser.getValueFrJsonObjData1 (/usr/lib/node_modules/homebridge-mi-aqara/parser/AccessoryParser.js:78:32)
    at MagicSquareSwitchVirtualFlip90Parser.getStatusLowBatteryCharacteristicValue (/usr/lib/node_modules/homebridge-mi-aqara/parser/AccessoryParser.js:127:30)
    at MagicSquareSwitchVirtualFlip90Parser.parserBatteryService (/usr/lib/node_modules/homebridge-mi-aqara/parser/AccessoryParser.js:156:42)
    at MagicSquareSwitchVirtualFlip90Parser.parserAccessories (/usr/lib/node_modules/homebridge-mi-aqara/parser/SwitchVirtualBasePressParser.js:63:18)
    at MagicSquareParser.parserAccessories (/usr/lib/node_modules/homebridge-mi-aqara/parser/DeviceParser.js:49:27)
    at ParseUtil.parserAccessories (/usr/lib/node_modules/homebridge-mi-aqara/lib/ParseUtil.js:112:29)
    at MagicSquareSwitchVirtualShakeAirParser.doSomething (/usr/lib/node_modules/homebridge-mi-aqara/parser/MagicSquareParser.js:359:33)
    at that.platform.sendWriteCommand.then.result (/usr/lib/node_modules/homebridge-mi-aqara/parser/SwitchVirtualBasePressParser.js:51:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:18838) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at MagicSquareSwitchVirtualShakeAirParser.callback2HB (/usr/lib/node_modules/homebridge-mi-aqara/parser/AccessoryParser.js:197:17)
    at /usr/lib/node_modules/homebridge-mi-aqara/parser/SwitchVirtualBasePressParser.js:57:34
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:18838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by MaFlax** [comment]
> I just installed the cube. And i see the switches in homekit. But when i select one i get:
> 
> ```
> [2018-11-19 21:38:24] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"write_ack","model":"sensor_cube.aqgl01","sid":"158d000287911e","short_id":14394,"data":"{\"voltage\":2995}"}
> [2018-11-19 21:38:24] [MiAqaraPlatform] [ERROR]SyntaxError: Unexpected token o in JSON at position 1
> [2018-11-19 21:38:24] [MiAqaraPlatform] [ERROR]SyntaxError: Unexpected token o in JSON at position 1
>     at JSON.parse (<anonymous>)
>     at MagicSquareSwitchVirtualFlip90Parser.getValueFrJsonObjData1 (/usr/lib/node_modules/homebridge-mi-aqara/parser/AccessoryParser.js:78:32)
>     at MagicSquareSwitchVirtualFlip90Parser.getStatusLowBatteryCharacteristicValue (/usr/lib/node_modules/homebridge-mi-aqara/parser/AccessoryParser.js:127:30)
>     at MagicSquareSwitchVirtualFlip90Parser.parserBatteryService (/usr/lib/node_modules/homebridge-mi-aqara/parser/AccessoryParser.js:156:42)
>     at MagicSquareSwitchVirtualFlip90Parser.parserAccessories (/usr/lib/node_modules/homebridge-mi-aqara/parser/SwitchVirtualBasePressParser.js:63:18)
>     at MagicSquareParser.parserAccessories (/usr/lib/node_modules/homebridge-mi-aqara/parser/DeviceParser.js:49:27)
>     at ParseUtil.parserAccessories (/usr/lib/node_modules/homebridge-mi-aqara/lib/ParseUtil.js:112:29)
>     at MagicSquareSwitchVirtualShakeAirParser.doSomething (/usr/lib/node_modules/homebridge-mi-aqara/parser/MagicSquareParser.js:359:33)
>     at that.platform.sendWriteCommand.then.result (/usr/lib/node_modules/homebridge-mi-aqara/parser/SwitchVirtualBasePressParser.js:51:34)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:189:7)
> (node:18838) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
>     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
>     at MagicSquareSwitchVirtualShakeAirParser.callback2HB (/usr/lib/node_modules/homebridge-mi-aqara/parser/AccessoryParser.js:197:17)
>     at /usr/lib/node_modules/homebridge-mi-aqara/parser/SwitchVirtualBasePressParser.js:57:34
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:189:7)
> (node:18838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
> ```

Try: `npm install homebridge-mi-aqara@0.7.3` or
       `sudo npm install homebridge-mi-aqara@0.7.3` to update to the newest version.
        Then restart your homebridge.

It is very important to update your gateway firmware to the newest version using the Mi Home app. My gateway version is: 1.4.1_159.0143 on Mainland China server.
