### ISSUE TITLE
PlugBase is giving ERROR

### ISSUE THREAD

**Issue by theo-69** [YinHangCode/homebridge-mi-aqara#195]
Since I updated to node.js 10.4.0 I am getting this ERROR

```
[6/15/2018, 2:38:46 PM] [MiAqaraPlatform] [ERROR]Error: {"voltage":3600,"status":"unknown","inuse":"0","power_consumed":"42","load_power":"0.00"}
(node:7377) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at PlugBaseOutletParser.callback2HB (/usr/local/lib/node_modules/homebridge-mi-aqara/parser/AccessoryParser.js:138:46)
    at /usr/local/lib/node_modules/homebridge-mi-aqara/parser/PlugBaseParser.js:88:30
(node:7377) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7377) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.jsprocess with a non-zero exit code.
```

I can switch once or twice but after that the homebridge crashes and I have to restart it.

**Comment by theo-69** [comment]
Getting this ERROR with the accessories now as well even updated to 10.4.1

**Comment by theo-69** [comment]
It alway happening with items that use voltage like plugs and LN Switches. Need help.
