### ISSUE TITLE
run homebridge 出现下面问题

### ISSUE THREAD

**Issue by 2645443857** [YinHangCode/homebridge-mi-aqara#21]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/h                                                                                                                     ap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodej                                                                                                                     s/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/h                                                                                                                     ap-nodejs/lib/Accessory.js:486:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:372:14        events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/h                                                                                                                     ap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodej                                                                                                                     s/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/h                                                                                                                     ap-nodejs/lib/Accessory.js:486:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:372:14

**Comment by a900927** [comment]
your homebridge it was already running,pls use ''service homebridge stop'' stop it or use ''service homebridge restart'' restart the service

**Comment by 2645443857** [comment]
what is wrong with the error message

**Comment by a900927** [comment]
@2645443857 51826端口被占用，应该是你的homebridge已经运行了

**Comment by 2645443857** [comment]
多谢，我今天晚上回去试试看看手机能不能控制
