### ISSUE TITLE
小米网关错误/usr/lib/node_modules/homebridge-mi-aqara/index.js:170

### ISSUE THREAD

**Issue by whb0219** [YinHangCode/homebridge-mi-aqara#239]
/usr/lib/node_modules/homebridge-mi-aqara/index.js:170
    if(Object.getOwnPropertyNames(hosts).length < Object.getOwnPropertyNames(gateways).length) {
                                                         ^

TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at MiAqaraPlatform.sendWhoisCommand (/usr/lib/node_modules/homebridge-mi-aqara/index.js:170:58)
    at API.<anonymous> (/usr/lib/node_modules/homebridge-mi-aqara/index.js:101:18)
    at emitNone (events.js:106:13)
    at API.emit (events.js:208:7)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:99:13)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)

运行homebridge -D后出现二维码与认证码，直接就出上面的错误退出，是什么情况啊？如果把config.json配置文件删除运行homebridge -D会出现二维码也不会退出。是哪里的问题？
NODEJS V8.12
homebridge-mi-aqarav0.7.2
debian v9

**Comment by tonymaibz** [comment]
遇到同样的问题，请问该如何解决。
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
node.js  v6.9.5
homebridge@0.4.45
homebridge-mi-aqara@0.7.2

**Comment by whb0219** [comment]
配置文件的错误，在网关mac和密码上面加上关键字就行了

发自我的 iPhone X

**Comment by whb0219** [comment]
配置文件错误

发自我的 iPhone X

**Comment by tonymaibz** [comment]
> {
> "platforms": [{
> "platform": "MiAqaraPlatform",
> "gateways": {
> "6409802da3b3": "02i44k56zrgg578b"
> }
> }]
> }
> 对比一下你们的配置文件就知道少什么了，现在网上的一些教程已经老了，没跟上作者的更新。

已经解决了，谢谢你！
