### ISSUE TITLE
Unhandled 'error' event，after upgrade to firmware 1.4.1_161.0157

### ISSUE THREAD

**Issue by sky2133** [YinHangCode/homebridge-mi-aqara#256]
[2019-1-2 21:07:00] [MiAqaraPlatform] [INFO]Aqara LAN protocol server is listening on port: 9898
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at EventedHTTPServer.listen (/usr/lib/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:128:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:97:10)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)

**Comment by Konfuze** [comment]
> Error: listen EADDRINUSE :::51826

There's another homebridge process already running and using 51826 port.

Try `killall homebridge` (or `sudo killall homebridge`)
