### ISSUE TITLE
run homebridge got error

### ISSUE THREAD

**Issue by alanclun** [YinHangCode/homebridge-mi-aqara#26]
[7/9/2017, 11:32:37 PM] Initializing MiAqaraPlatform platform...
Load homebridge-aqara.AqaraPlatform
/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:26
  if (config['sensor_names']) {
            ^

TypeError: Cannot read property 'sensor_names' of null
    at new AqaraAccessoryFactory (/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:26:13)
    at new AqaraPlatform (/usr/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:27:18)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:315:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:82:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by YinHangCode** [comment]
make sure use homebridge-mi-aqara, not homebridge-aqara.

**Comment by iCarl** [comment]
Also, uninstall homebridge-aqara before using homebridge-mi-aqara.

**Comment by alanclun** [comment]
if i use mi-aqara, i can't find the homebridge in ihome

**Comment by stonerocky** [comment]
how to unintall plugins? @iCarl

**Comment by iCarl** [comment]
"sudo npm unistall homebridge-aqara"
