### ISSUE TITLE
 [MiAqaraPlatform] [ERROR]TypeError: Cannot read property 'ip' of null

### ISSUE THREAD

**Issue by wangxingguo** [YinHangCode/homebridge-mi-aqara#278]
config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "89:88:55:66:1A:23",
        "port": 51826,
        "pin": "678-66-964"
    },
    "platforms": [
        {
            "platform": "MiAqaraPlatform",
            "bindAddress": "192.168.18.9",   //Raspberry Pi ip
            "gateways": {
                "04cf8cb87a38": {
                    "password": "39E92BC3402C45E8",
                    "ip":"192.168.18.10"    //xiaomi gateway ip
                }
            }
        }
    ]
}

homebridge -D
[2019-12-28 2:46:24 PM] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"virtual_iam","sid":"04cf8cb87a38","port":"9898","ip":"192.168.18.10"}
[2019-12-28 2:46:24 PM] [MiAqaraPlatform] [DEBUG][Send]{"cmd":"read", "sid":"04cf8cb87a38"}
[2019-12-28 2:46:24 PM] [MiAqaraPlatform] [INFO]Aqara LAN protocol server is listening on port: 9898
[2019-12-28 2:46:24 PM] Homebridge is running on port 51826.
[2019-12-28 2:46:24 PM] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"read_ack","model":"gateway","sid":"4cf8cb87a38","short_id":0,"data":"{\"rgb\":352321535,\"illumination\":1292,\"proto_version\":\"1.1.2\"}"}
[2019-12-28 2:46:24 PM] [MiAqaraPlatform] [DEBUG][Send]{"cmd":"get_id_list"}
[2019-12-28 2:46:24 PM] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"get_id_list_ack","sid":"04cf8cb87a38","token":"FvobjVTAjbO2MD1z","data":"[\"158d00035f732c\"]"}
[2019-12-28 2:46:25 PM] [MiAqaraPlatform] [ERROR]TypeError: Cannot read property 'ip' of null
[2019-12-28 2:46:25 PM] [MiAqaraPlatform] [ERROR]TypeError: Cannot read property 'ip' of null
    at Promise (/usr/local/lib/node_modules/homebridge-mi-aqara/index.js:828:34)
    at new Promise (<anonymous>)
    at MiAqaraPlatform.sendReadCommand (/usr/local/lib/node_modules/homebridge-mi-aqara/index.js:824:12)
    at Timeout.setInterval [as _onTimeout] (/usr/local/lib/node_modules/homebridge-mi-aqara/index.js:579:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2019-12-28 2:46:25 PM] [MiAqaraPlatform] [DEBUG]read gateway(4cf8cb87a38) device list finished. size: 1
[2019-12-28 2:51:18 PM] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"report","model":"gateway","sid":"04cf8cb87a38","short_id":0,"data":"{\"rgb\":352321535,\"illumination\":1292}"}

**Comment by wangxingguo** [comment]
Router info:




hassbian | b8:27:eb:b4:73:b3 | 192.168.18.9 | DHCP | SSID1 |  
lumi-gateway-v3_miio134548234 | 04:cf:8c:b8:7a:38 | 192.168.18.10 | DHCP | SSID1

**Comment by wangxingguo** [comment]
@YinHangCode

**Comment by wangxingguo** [comment]
@YinHangCode 能否帮忙看看,谢谢!
