### ISSUE TITLE
Invalid Key

### ISSUE THREAD

**Issue by b4life75** [YinHangCode/homebridge-mi-aqara#292]
Can someone kindly advise what's the issue of the invalid key? It works once after reboot and when pressing on the same device this error happens... everytime i reboot homebridge it works once and will not work anymore.

Thanks.

[10/27/2020, 10:58:39 PM] [MiAqaraPlatform] [DEBUG][Send]{"cmd":"write","model":"ctrl_neutral2","sid":"158d00024df626","data":{"channel_0":"on", "key": "8c1609a94c78d64fe4e651b234f00eae"}}
[10/27/2020, 10:58:39 PM] [MiAqaraPlatform] [DEBUG](MQTT)(Send Success)Topic: /homebridge-mi-aqara, Message: {"cmd":"write_ack","sid":"158d00024df626","data":"{\"error\":\"Invalid key\"}"}
[10/27/2020, 10:58:39 PM] [MiAqaraPlatform] [DEBUG](MQTT)(Send Success)Topic: /homebridge-mi-aqara/write_ack, Message: {"cmd":"write_ack","sid":"158d00024df626","data":"{\"error\":\"Invalid key\"}"}
[10/27/2020, 10:58:39 PM] [MiAqaraPlatform] [DEBUG](MQTT)(Send Success)Topic: /homebridge-mi-aqara/158d00024df626, Message: {"cmd":"write_ack","sid":"158d00024df626","data":"{\"error\":\"Invalid key\"}"}
[10/27/2020, 10:58:39 PM] [MiAqaraPlatform] [DEBUG](MQTT)(Send Success)Topic: /homebridge-mi-aqara/158d00024df626/write_ack, Message: {"cmd":"write_ack","sid":"158d00024df626","data":"{\"error\":\"Invalid key\"}"}
[10/27/2020, 10:58:39 PM] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"write_ack","sid":"158d00024df626","data":"{\"error\":\"Invalid key\"}"}
[10/27/2020, 10:58:39 PM] [MiAqaraPlatform] [ERROR]Error: Invalid key
[10/27/2020, 10:58:39 PM] [MiAqaraPlatform] [ERROR]Error: Invalid key
    at MiAqaraPlatform.parseMessage (C:\Users\PENTEST\AppData\Roaming\npm\node_modules\homebridge-mi-aqara\index.js:598:26)
    at Socket.emit (events.js:314:20)
    at UDP.onMessage (dgram.js:921:8)

**Comment by albertc180** [comment]
@b4life75 Did you solved that issue? I'm experiencing the same from few days.
