### ISSUE TITLE
依旧存在home app 里不能使用无线开关的问题

### ISSUE THREAD

**Issue by Fetiz** [YinHangCode/homebridge-mi-aqara#37]
home app 内可以看到如下图的提示
![img_0128](https://user-images.githubusercontent.com/20578132/28681378-e4504544-732b-11e7-9996-09d132bb44bb.png)
![img_0129](https://user-images.githubusercontent.com/20578132/28681443-1cbca4f4-732c-11e7-8ee1-6f26e862ee39.png)

在米家 app 中可以看到无线开关的型号是 lumi.sensor_switch.v2 但是开关的外观却是第一代的米家无线开关外观 希望大佬能帮忙解决 已经在 docker 里重置了好多次 homebridge 了每次都只有这一个插件无法正常工作

**Comment by YinHangCode** [comment]
第二代无线开关么？这个好像网关固件要升级到最新版才行

**Comment by Fetiz** [comment]
@YinHangCode 在米家app里网关的固件已经升级到1.4.1_148.0143目前检查无最新版本固件

**Comment by YinHangCode** [comment]
1.4.1_148.0143是最新，按下按钮后看下日志里的debug信息能搜到按钮的report消息么？

**Comment by Fetiz** [comment]
docker的homebridge插件里日志是这样的 由于按钮在米家里跟yeelight的彩灯关联了单击的动作 就这样显示了 米家app里目前没有看到


![8mq2p181fkg0kj59 kf2wc](https://user-images.githubusercontent.com/20578132/28704703-c2c233d8-739e-11e7-9366-84ab7918d094.png)

**Comment by YinHangCode** [comment]
额 docker我没研究过 不是太懂 我的意思是说 启动homebridge的时候 不是会有日志打印么 用-D的参数启动homebridge 会打出每个插件的report原始信息，当按下按钮的时候，这个日志里面有按钮发来的report信息么？

**Comment by Fetiz** [comment]
@YinHangCode 设备现在不在身边等下班了回家ssh群晖看看是怎么回事

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Fetiz** [comment]
`oot@Fetiz-NAS:/# homebridge -D -U
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.0
npm info ok 
[7/28/2017, 11:56:04 AM] Loaded plugin: homebridge-airnow
[7/28/2017, 11:56:04 AM] Registering accessory 'homebridge-airnow.airnow'
[7/28/2017, 11:56:04 AM] ---
[7/28/2017, 11:56:04 AM] Loaded plugin: homebridge-mi-aqara
[7/28/2017, 11:56:04 AM] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[7/28/2017, 11:56:04 AM] ---
[7/28/2017, 11:56:04 AM] Loaded plugin: homebridge-synology
[7/28/2017, 11:56:04 AM] Registering accessory 'homebridge-synology.Synology'
[7/28/2017, 11:56:04 AM] ---
failed to load BLE module!
[7/28/2017, 11:56:04 AM] Loaded plugin: homebridge-yeelight
[7/28/2017, 11:56:04 AM] Registering platform 'homebridge-yeelight.yeelight'
[7/28/2017, 11:56:04 AM] ---
[7/28/2017, 11:56:04 AM] Loaded config.json with 2 accessories and 2 platforms.
[7/28/2017, 11:56:04 AM] ---
[7/28/2017, 11:56:04 AM] Loading 2 platforms...
[7/28/2017, 11:56:04 AM] Initializing MiAqaraPlatform platform...
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][INFO]**************************************************************
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][INFO]*                 MiAqaraPlatform By YinHang                 *
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][INFO]* github: https://github.com/YinHangCode/homebridge-mi-aqara *
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][INFO]*                                        QQ Group: 107927710 *
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][INFO]**************************************************************
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][INFO]start success...
[7/28/2017, 11:56:04 AM] [yeelight] Initializing yeelight platform...
[7/28/2017, 11:56:04 AM] [yeelight] YeePlatform Init
[7/28/2017, 11:56:04 AM] Loading 2 accessories...
[7/28/2017, 11:56:04 AM] [Air Outside] Initializing airnow accessory...
[7/28/2017, 11:56:04 AM] [Air Outside] AirNow using provider aqicn and Polling (minutes) is: 30
[7/28/2017, 11:56:04 AM] [DSKID] Initializing Synology accessory...
[7/28/2017, 11:56:04 AM] [DSKID] s
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 199-30-903 │     
    └────────────┘     
                       
[7/28/2017, 11:56:04 AM] [yeelight] DidFinishLaunching
no ble cap, skip ble device discovery
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][DEBUG]Aqara server is listening on port 9898.
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::53699
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:509:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:10)
`
这是在homebridge的后台打印出的所有信息 发生错误后就自动中断退出了

**Comment by Fetiz** [comment]
@YinHangCode 这是打印出来的所有的内容 看起来似乎js上出了问题 但是在homebridge在docker里自己的日志上却是没问题的


```bash
root@Fetiz-NAS:/# homebridge -D -U
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.0
npm info ok 
[7/28/2017, 11:56:04 AM] Loaded plugin: homebridge-airnow
[7/28/2017, 11:56:04 AM] Registering accessory 'homebridge-airnow.airnow'
[7/28/2017, 11:56:04 AM] ---
[7/28/2017, 11:56:04 AM] Loaded plugin: homebridge-mi-aqara
[7/28/2017, 11:56:04 AM] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[7/28/2017, 11:56:04 AM] ---
[7/28/2017, 11:56:04 AM] Loaded plugin: homebridge-synology
[7/28/2017, 11:56:04 AM] Registering accessory 'homebridge-synology.Synology'
[7/28/2017, 11:56:04 AM] ---
failed to load BLE module!
[7/28/2017, 11:56:04 AM] Loaded plugin: homebridge-yeelight
[7/28/2017, 11:56:04 AM] Registering platform 'homebridge-yeelight.yeelight'
[7/28/2017, 11:56:04 AM] ---
[7/28/2017, 11:56:04 AM] Loaded config.json with 2 accessories and 2 platforms.
[7/28/2017, 11:56:04 AM] ---
[7/28/2017, 11:56:04 AM] Loading 2 platforms...
[7/28/2017, 11:56:04 AM] Initializing MiAqaraPlatform platform...
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][INFO]**************************************************************
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][INFO]*                 MiAqaraPlatform By YinHang                 *
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][INFO]* github: https://github.com/YinHangCode/homebridge-mi-aqara *
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][INFO]*                                        QQ Group: 107927710 *
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][INFO]**************************************************************
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][INFO]start success...
[7/28/2017, 11:56:04 AM] [yeelight] Initializing yeelight platform...
[7/28/2017, 11:56:04 AM] [yeelight] YeePlatform Init
[7/28/2017, 11:56:04 AM] Loading 2 accessories...
[7/28/2017, 11:56:04 AM] [Air Outside] Initializing airnow accessory...
[7/28/2017, 11:56:04 AM] [Air Outside] AirNow using provider aqicn and Polling (minutes) is: 30
[7/28/2017, 11:56:04 AM] [DSKID] Initializing Synology accessory...
[7/28/2017, 11:56:04 AM] [DSKID] s
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 199-30-903 │     
    └────────────┘     
                       
[7/28/2017, 11:56:04 AM] [yeelight] DidFinishLaunching
no ble cap, skip ble device discovery
[7/28/2017, 11:56:04 AM] [MiAqaraPlatform][DEBUG]Aqara server is listening on port 9898.
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::53699
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:509:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:10)
root@Fetiz-NAS:/# 
```

**Comment by YinHangCode** [comment]
端口被占用，你启动了两次程序 = =#

**Comment by Fetiz** [comment]
@YinHangCode 重启了群晖并且重启了docker容器后再ssh里还是这样 但是还是报出如此的错误 端口如果被占用的话不应该在是这样的报错 目前怀疑是node.js 版本的问题 是7.10，升级下8.2.1试试

**Comment by YinHangCode** [comment]
ps -eaf | grep homebridge
看看

**Comment by Fetiz** [comment]
@YinHangCode 
```
root@Fetiz-NAS:/# ps -eaf | grep homebridge                                                  
root        83     1  0 13:53 console  00:00:02 homebridge                                   
root       204   112  0 14:03 ?        00:00:00 grep homebridge 
```

**Comment by YinHangCode** [comment]
homebridge已经启动了 pid是83

**Comment by a900927** [comment]
我升级了nodejs 8也是运行不了。退回去6.x就ok了

**Comment by YinHangCode** [comment]
我用的v7.9.0

**Comment by Fetiz** [comment]
@YinHangCode @a900927 docker的homebridge打包者是 [https://github.com/marcoraddatz/homebridge-docker](https://github.com/marcoraddatz/homebridge-docker) 
其中包含了7.10版本的nodejs 之前看到的报错是7.10独有的

**Comment by Fetiz** [comment]
在降级至7.9.0的nodejs后依旧不能正常使用button

**Comment by Fetiz** [comment]
经过排查 删掉所有的插件后发现即便是纯净的docker homebridge也无法homebridge -D 已经向原开发者提交了issue

**Comment by YinHangCode** [comment]
你在启动之前执行ps -eaf | grep homebridge看看 我觉得你是homebridge启动重复了

**Comment by Fetiz** [comment]
@YinHangCode 在容器的 bash 里执行结果如下
```bash
root@Fetiz-NAS:/# ps -eaf | grep homebridge                                                  
root        79     1  0 01:30 console  00:00:01 homebridge                                   
root       116   108  0 01:40 ?        00:00:00 grep homebridge   
```
在 nas 的 ssh bash 中执行如下
```bash
root@Fetiz-NAS:~# ps -eaf | grep homebridge
root      9037  3830  0 09:39 pts/5    00:00:00 grep --color=auto homebridge
```

**Comment by YinHangCode** [comment]
从结果上看 已经启动homebridge了 pid是79

**Comment by Fetiz** [comment]
是启动了 但是在homebridge里 还是不能正确使用button

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by YinHangCode** [comment]
看看日志里有没有report信息

**Comment by Fetiz** [comment]
大概明白了为什么会无法打印 因为 docker 自己占用了一个 bash 用于不断地输出-D，目前将配置过程的截图截取了出来。
<img width="1309" alt="screen shot 2017-07-29 at 12 38 33" src="https://user-images.githubusercontent.com/20578132/28742153-687e7f68-745b-11e7-9944-b74c06b27bf8.png">
<img width="1294" alt="screen shot 2017-07-29 at 12 38 42" src="https://user-images.githubusercontent.com/20578132/28742154-69bc6886-745b-11e7-8d06-ecc81cc66a4d.png">

**Comment by YinHangCode** [comment]
后面的日志？

**Comment by Fetiz** [comment]
![screen shot 2017-07-29 at 13 50 53](https://user-images.githubusercontent.com/20578132/28742538-053f0256-7465-11e7-9505-9a6a562432fc.png)
在日志里可以看出 button 是被正确识别了的 但是不知道为什么 home app 里一直显示 not support

**Comment by a900927** [comment]
IOS11会出现这种情况

**Comment by Fetiz** [comment]
@a900927 所以就只能降级至 iOS 10然后正常使用吗 那等到升级 iOS 11后还是会出现这个问题啊

**Comment by YinHangCode** [comment]
ios11正式版还没发布 测试版肯定有很多问题

**Comment by Fetiz** [comment]
好的谢谢大佬 感觉可以关掉这个issue了 估计ios 11 出来了 可能homebridge就会更新了

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by YinHangCode** [comment]
嗯 应该是
