### ISSUE TITLE
Homebridge crash when i turn on/off gateway light

### ISSUE THREAD

**Issue by frolov32** [YinHangCode/homebridge-mi-aqara#4]
Hi! 
When i try to turn on or off gateway light i instantly get the error message:

`TypeError: Key must be a buffer
    at TypeError (native)
    at new Cipheriv (crypto.js:191:16)
    at Object.Cipheriv (crypto.js:189:12)
    at MiAqaraPlatform.getWriteKeyByDeviceSid (/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:252:25)
    at GatewayParser.controlLight (/usr/local/lib/node_modules/homebridge-mi-aqara/DeviceParsers/GatewayParser.js:166:29)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-aqara/DeviceParsers/GatewayParser.js:122:22)
    at emitMany (events.js:127:13)
    at Characteristic.emit (events.js:201:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:740:22)
`

**Comment by YinHangCode** [comment]
make sure you are running the latest version(0.3.1 later).
If you have run the latest version, and error still, please provide your nodejs version, homebridge version, ios version.

**Comment by frolov32** [comment]
I running the latest version so far - 0.3.3
Homebridge - 0.4.20
Node - 6.9.1
IOS - 10.3.2 
Lux parameter changes correctly.

**Comment by YinHangCode** [comment]
okay.

**Comment by substa** [comment]
Same problem here...

Homebridge - 0.4.20
Node - 6.11.0
iOs - 10.3.2
