### ISSUE TITLE
加载配置文件失败Cannot read property 'sensor_names' of null

### ISSUE THREAD

**Issue by liubiqu** [YinHangCode/homebridge-mi-aqara#41]
config.json

```
{
    "bridge": {
        "name": "Homebridge", 
        "username": "CC:22:3D:E3:CE:30", 
        "port": 51826, 
        "pin": "031-45-154"
    }, 
    "platforms": [
        {
            "platform": "AqaraPlatform", 
            "sid": ["f0b429aa18bd"], 
            "password": ["6B0D69DCF7A04132"]
        }
    ]
}
```

```
06] Loaded plugin: homebridge-aqara
[2017-8-1 09:56:06] Registering platform 'homebridge-aqara.AqaraPlatform'
[2017-8-1 09:56:06] ---
[2017-8-1 09:56:06] Loaded plugin: homebridge-mi-aqara
[2017-8-1 09:56:06] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[2017-8-1 09:56:06] ---
[2017-8-1 09:56:06] Loaded config.json with 0 accessories and 1 platforms.
[2017-8-1 09:56:06] ---
[2017-8-1 09:56:06] Loading 1 platforms...
[2017-8-1 09:56:06] Initializing AqaraPlatform platform...
Load homebridge-mi-aqara.MiAqaraPlatform
/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:181
    var sid = config['sid'];
                    ^

TypeError: Cannot read property 'sid' of null
    at MiAqaraPlatform.loadConfig (/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:181:21)
    at new MiAqaraPlatform (/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:148:10)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:315:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:82:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by liubiqu** [comment]
``` 
"platform": "AqaraPlatform",   
```
改为
```
"platform": "MiAqaraPlatform", 
```

但又出现新的错误提示：
```
Load homebridge-aqara.AqaraPlatform
/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:26
  if (config['sensor_names']) {
            ^

TypeError: Cannot read property 'sensor_names' of null
    at new AqaraAccessoryFactory (/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:26:13)
    at new AqaraPlatform (/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:27:18)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:315:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:82:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by liubiqu** [comment]
/sampleConfig.json  也没有看到sensor_names这个配置呀，请调整一下。

**Comment by a900927** [comment]
怎么有点小问题就发提问啊。看错误代码还不知道那里有问题？

**Comment by liubiqu** [comment]
Also, uninstall homebridge-aqara before using homebridge-mi-aqara.   解决了

**Comment by Raccooon** [comment]
This issue is really helpful.

**Comment by YinHangCode** [comment]
这个不是homebridge-aqara的bug么，怎么问到这里了。。。感觉是走错了片场 ^_^
