### ISSUE TITLE
plugin always load even when not configured

### ISSUE THREAD

**Issue by imperialjoy** [YinHangCode/homebridge-mi-aqara#49]
First of all, excellent plugin!  I have a motion sensor, door and button, lux, night light and it all works perfectly and FAST!

Problem:
I run a separate version of homebridge for each plugin, it greatly increases stability. I noticed this plugin loads even if it is not configured to in config.json.  Plugins should only load if configured.

/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:181
    var sid = config['sid'];
                    ^

TypeError: Cannot read property 'sid' of null
    at MiAqaraPlatform.loadConfig (/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:181:21)
    at new MiAqaraPlatform (/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:148:10)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:315:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:82:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

**Comment by YinHangCode** [comment]
this bug is fixed in version 0.4.4, I haven't uploaded yet, wait a moment.
