### ISSUE TITLE
I can't get the built in light to work

### ISSUE THREAD

**Issue by iCarl** [YinHangCode/homebridge-mi-aqara#51]
- Tried using lower case letters in both sid and password,
- Tried using capital letters in both sid and password,
- Tried capital in sid but lower in password,
- Tried lower in sid and capital in password.

I've tried deleting the cachedAccessories file, creating a new Homebridge-config.

crypto.js:191
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

```
TypeError: Key must be a buffer
    at TypeError (native)
    at new Cipheriv (crypto.js:191:16)
    at Object.Cipheriv (crypto.js:189:12)
    at MiAqaraPlatform.getWriteKeyByDeviceSid (/usr/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:266:25)
    at GatewayParser.controlLight (/usr/lib/node_modules/homebridge-mi-aqara/DeviceParsers/GatewayParser.js:174:29)
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge-mi-aqara/DeviceParsers/GatewayParser.js:115:22)
    at emitMany (events.js:127:13)
    at Characteristic.emit (events.js:201:7)
    at Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:733:22)
```

Sometimes it says "Not Supported"

iOS 11 Beta 5
Node v6.9.5
Homebridge v0.4.22
Homebridge-mi-aqara v0.4.4

Someone please help

**Comment by iCarl** [comment]
Same problem with Homebridge-mi-aqara version 0.5.1

**Comment by YinHangCode** [comment]
“Not Supported” is ios 11 beta bug.
use ios 10.3.3 or wair ios 11 release.

**Comment by iCarl** [comment]
"Not Supported" disappears after I restart Homebridge, but it still crashes when I try to turn on the light.

**Comment by YinHangCode** [comment]
@iCarl update to 0.5.1

**Comment by stich86** [comment]
@YinHangCode 

hi,
i'm running iOS 10.3.3 and latest version of home bridge\miaqara

i've light control on the iOS home app but cannot do anything.. on/off/change color/change brightness  to working :(

is it normal?

**Comment by YinHangCode** [comment]
@stich86 make sure your gateway sid and password is right.

**Comment by stich86** [comment]
i've done a TCPDUMP and I see this error when try to turn on light:

{"cmd":"write_ack","sid":"34ce009075","data":"{\"error\":\"Invalid.key\"}"}

but the password is the one (with letters and number) displayed on the local enable protocol right?

**Comment by YinHangCode** [comment]
@stich86 
sid: lower case without colon
password: keep original, case sensitive.

"error":"Invalid.key", It looks like key isn't right, for the key rules, refer to the [official document](https://github.com/louisZL/lumi-gateway-local-api).

**Comment by stich86** [comment]
ok it was the case sensitive.. may be it's better to clarify this aspect on the README, because you have put all letter in lowercase while the MIAPP use uppercase

thanks!

**Comment by YinHangCode** [comment]
@stich86 
password, this uppercase and lowercase all exists. ios normally uppercase and android normally lowercase.

**Comment by iCarl** [comment]
I am currently using iOS 11 GM, and still getting Not Supported.
Do I have to reset the Homebridge pairing?

**Comment by iCarl** [comment]
Same error message as before:

```
TypeError: Key must be a buffer
    at TypeError (native)
    at new Cipheriv (crypto.js:191:16)
    at Object.Cipheriv (crypto.js:189:12)
    at MiAqaraPlatform.getWriteKeyByDeviceSid (/usr/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:266:25)
    at GatewayParser.controlLight (/usr/lib/node_modules/homebridge-mi-aqara/DeviceParsers/GatewayParser.js:174:29)
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge-mi-aqara/DeviceParsers/GatewayParser.js:115:22)
    at emitMany (events.js:127:13)
    at Characteristic.emit (events.js:201:7)
    at Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:733:22)
```

**Comment by iCarl** [comment]
For some reason I've been using the "gw_mac" instead of "mac".
Sorry for this
