### ISSUE TITLE
在homekit中可以看到zigbee插座，点按开关却无法控制插座的开关。

### ISSUE THREAD

**Issue by jgao3333** [YinHangCode/homebridge-mi-aqara#58]
首先感谢大神开发这个插件~膜拜

我的问题是在homekit (ios10)中可以看到zigbee插座，点按开关后插座没有任何反应，但温/湿度传感器可以正常运行.
还有一点疑惑: 关于sid我们应该用小写
但password是要用小写还是大写?
我是试过小写和大写,都仍旧不能控制插座的开关.

感谢!

**Comment by YinHangCode** [comment]
sid是小写去冒号
密码是大写就大写 小写就小写 依照原文

**Comment by jgao3333** [comment]
感谢大神回复,我的密码是按照原文写的 sid也小写去冒号了 但是 仍旧控制不了 zigbee插座的开关. 温湿度却是正常的, siri也能查温湿度.

**Comment by jgao3333** [comment]
![image](https://user-images.githubusercontent.com/31022507/29741431-7841b55a-8a9f-11e7-9326-a8531771a582.png)

**Comment by YinHangCode** [comment]
读取设备信息是不需要密码的 所以可以正常
你启动homebridge的时候 加上-D的参数 这样可以打印出 给网关发送的原始数据 可以看一下

**Comment by jgao3333** [comment]
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[8/26/2017, 12:52:14 PM] Loaded plugin: homebridge-mi-aqara
[8/26/2017, 12:52:14 PM] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[8/26/2017, 12:52:14 PM] ---
[8/26/2017, 12:52:14 PM] Loaded config.json with 0 accessories and 1 platforms.
[8/26/2017, 12:52:14 PM] ---
[8/26/2017, 12:52:14 PM] Loading 1 platforms...
[8/26/2017, 12:52:14 PM] Initializing MiAqaraPlatform platform...
[8/26/2017, 12:52:14 PM] [MiAqaraPlatform][INFO]**************************************************************
[8/26/2017, 12:52:14 PM] [MiAqaraPlatform][INFO]           MiAqaraPlatform v0.5.1 By YinHang
[8/26/2017, 12:52:14 PM] [MiAqaraPlatform][INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-aqara
[8/26/2017, 12:52:14 PM] [MiAqaraPlatform][INFO]                                         QQ Group: 107927710
[8/26/2017, 12:52:14 PM] [MiAqaraPlatform][INFO]**************************************************************
[8/26/2017, 12:52:14 PM] [MiAqaraPlatform][INFO]start success...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 233-78-123 │
    └────────────┘

[8/26/2017, 12:52:15 PM] [MiAqaraPlatform][DEBUG]Aqara server is listening on port 9898.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:521:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:10)

**Comment by jgao3333** [comment]
大神是否因为我的系统时间不对呢？我看这上面的时间显示的是12点多PM 现在时间是21:00

**Comment by YinHangCode** [comment]
这个错误 应该是你启动了两个homebridge

**Comment by jgao3333** [comment]
请问大神 这个应该怎么调整呢？ 谢谢

**Comment by jgao3333** [comment]
当时装完homebridge 并配置好以后， 我参考威锋论坛 老高 的步骤 执行的如下命令 会不会和这个有关呢？：
####将homebridge设置成随系统启动######
cd /

sudo useradd --system homebridge

sudo mkdir /var/homebridge

sudo cp ~/.homebridge/config.json /var/homebridge/

sudo cp -r ~/.homebridge/persist /var/homebridge

sudo chmod -R 0777 /var/homebridge

cd /etc/default

sudo nano homebridge

#########将下面的内容复制粘贴进去，然后Ctrl+X，然后Y，回车，保存退出####

# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
HOMEBRIDGE_OPTS=-U /var/homebridge

# If you uncomment the following line, homebridge will log more 
# You can display this via systemd's journalctl: journalctl -f -u homebridge
# DEBUG=*

####分界线#####################################

cd /etc/systemd/system

sudo nano homebridge.service

#########将下面的内容复制粘贴进去，然后Ctrl+X，然后Y，回车，保存退出####

[Unit]
Description=Node.js HomeKit Server 
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/lib/node_modules/homebridge/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target

####分界线#####################################

cd /

sudo systemctl daemon-reload

sudo systemctl enable homebridge

sudo systemctl start homebridge

sudo systemctl status homebridge

sudo reboot      ####重启树莓派####
