### ISSUE TITLE
homebridge-mi-aqara插件是否和homebridge-assistant插件冲突？

### ISSUE THREAD

**Issue by FaintGhost** [YinHangCode/homebridge-mi-aqara#6]
配置文件如下

{
	"bridge": {
		"name": "Homebridge",
		"username": "28:6C:07:89:21:55",
		"port": 51826,
		"pin": "123-45-678"
	},
	"platforms": [{
			"platform": "HomeAssistant",
			"name": "HomeAssistant",
			"host": "http://192.168.31.38:8123",
			"password": "raspberry",
			"supported_types": ["fan", "garage_door", "input_boolean", "light", "lock", "media_player", "rollershutter", "scene", "switch"]
		},
		{
			"platform": "MiAqaraPlatform",
			"sid": ["286c07892155"],
			"password": ["AFCFEB45925F4488"]
		}
	]
}

运行返回如下
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[6/16/2017, 2:02:27 PM] Loaded plugin: homebridge-homeassistant
[6/16/2017, 2:02:27 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[6/16/2017, 2:02:27 PM] ---
[6/16/2017, 2:02:27 PM] Loaded plugin: homebridge-mi-aqara
[6/16/2017, 2:02:27 PM] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[6/16/2017, 2:02:27 PM] ---
[6/16/2017, 2:02:27 PM] Loaded plugin: homebridge-aqara
[6/16/2017, 2:02:27 PM] Registering platform 'homebridge-aqara.AqaraPlatform'
[6/16/2017, 2:02:27 PM] ---
[6/16/2017, 2:02:27 PM] Loaded config.json with 0 accessories and 2 platforms.
[6/16/2017, 2:02:27 PM] ---
[6/16/2017, 2:02:27 PM] Loading 2 platforms...
[6/16/2017, 2:02:28 PM] [HomeAssistant] Initializing HomeAssistant platform...
[6/16/2017, 2:02:28 PM] [HomeAssistant] Fetching HomeAssistant devices.
[6/16/2017, 2:02:28 PM] Initializing MiAqaraPlatform platform...
Load homebridge-aqara.AqaraPlatform
/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:26
  if (config['sensor_names']) {
            ^

TypeError: Cannot read property 'sensor_names' of null
    at new AqaraAccessoryFactory (/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:26:13)
    at new AqaraPlatform (/node_modules/homebridge-aqara/lib/AqaraPlatform.js:27:18)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:315:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:82:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

但是使用homebridge-aqara插件就可以运行。 但是你做的插件兼容的设备更多，想问一下是否有冲突？谢谢！

**Comment by FaintGhost** [comment]
刚才已经解决了 删除插件并删除/node_modules/homebridge-aqara/文件夹 然后重新安装就好了
