### ISSUE TITLE
Wall plug crash homebridge

### ISSUE THREAD

**Issue by prbreezy** [YinHangCode/homebridge-mi-aqara#64]
Hi

I sucessfully install and have homebridge works with the mi-aqara pluging but anytime I press the wall plug bottom homebridge crash below the log 

`events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: MAX_CLIENTS=6
    at Connection.onStanza (/opt/node/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:355:17)
    at StreamParser.<anonymous> (/opt/node/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:90:13)
    at StreamParser.emit (events.js:182:7)
    at SaxLtx.<anonymous> (/opt/node/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:90:13)
    at SaxLtx.emit (events.js:182:7)
    at SaxLtx._handleTagOpening (/opt/node/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/opt/node/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/opt/node/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/opt/node/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:534:20)
pi@raspberrypi:~ $ ls`

**Comment by prbreezy** [comment]
Hello
Anyone is facing the issue?
Cheers

**Comment by ZhijieLiu029** [comment]
I have the same issue.

**Comment by theo-69** [comment]
its the harmony hub, please close issue
