### ISSUE TITLE
Nice plugin! but Gateway light issue

### ISSUE THREAD

**Issue by rqui** [YinHangCode/homebridge-mi-aqara#7]
When I'm trying to power on the gateway light throws me that error:

crypto.js:191
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

TypeError: Key must be a buffer
    at new Cipheriv (crypto.js:191:16)
    at Object.Cipheriv (crypto.js:189:12)
    at MiAqaraPlatform.getWriteKeyByDeviceSid (/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:252:25)
    at GatewayParser.controlLight (/usr/local/lib/node_modules/homebridge-mi-aqara/DeviceParsers/GatewayParser.js:166:29)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-aqara/DeviceParsers/GatewayParser.js:107:22)
    at emitMany (events.js:127:13)
    at Characteristic.emit (events.js:201:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:756:22)
    at Array.forEach (native)

node v: 7.0.0
npm v: 5.0.3
Homebridge v: 0.4.20
Plugin v: 0.3.3
iOS v: 10.3.2

Thanks!

**Comment by Brklnbnc** [comment]
Hi there. I experience the exact same problem with the Aqara gateway light switch:

crypto.js:190
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^
TypeError: Key must be a buffer
    at TypeError (native)
    at new Cipheriv (crypto.js:190:16)
    at Object.Cipheriv (crypto.js:188:12)
    at MiAqaraPlatform.getWriteKeyByDeviceSid (/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:252:25)
    at GatewayParser.controlLight (/usr/local/lib/node_modules/homebridge-mi-aqara/DeviceParsers/GatewayParser.js:166:29)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-aqara/DeviceParsers/GatewayParser.js:122:22)
    at emitMany (events.js:127:13)
    at Characteristic.emit (events.js:201:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:756:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:701:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:201:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

node: 6.5.0
npm: 4.6.1
Homebridge: 0.4.20
mi-aqara plugin: 0.3.3
iOS: 10.3.3 beta 4

**Comment by sendorm** [comment]
can confirm. I also have a problem with xiaomi gateway lights.

**Comment by sendorm** [comment]
Try changing the password to all capital letters.

**Comment by rqui** [comment]
Already in capital letters, from the beggining, did solved the fail for you?

**Comment by sendorm** [comment]
I didn't get the chance to test it yet. But it fixed for others. 
https://github.com/YinHangCode/homebridge-mi-aqara/issues/15

**Comment by rqui** [comment]
Does anyone has working gateway lights?

**Comment by hzww** [comment]
after i installed the plugin, the lux sensor and the gateway light appear in home app, the lux sensor just show the lux information and the gateway light can be turn on/off and set in color and the percent of the light.
it works, no problem

**Comment by rqui** [comment]
Can you put your node and npm version?

Thanks.

**Comment by rqui** [comment]
Finally got working, the sid must to be in lowercase....
