### ISSUE TITLE
Error at loading when platform defined in config.json

### ISSUE THREAD

**Issue by TheTherminator** [YinHangCode/homebridge-mi-aqara#71]
**Hi Guys,

when I am running my homebridge without the Gateway in my config.json - everyhing okay. 
Mi-aqara Plugin loaded - no error.**

(excerpt of my log)
Thu Sep 28 2017 16:09:36 GMT-0400 (EDT) > [Thu Sep 28 2017 16:09:36 GMT-0400 (EDT)] Loaded plugin: homebridge-delay-switch
Thu Sep 28 2017 16:09:36 GMT-0400 (EDT) > [Thu Sep 28 2017 16:09:36 GMT-0400 (EDT)] Registering accessory 'homebridge-delay-switch.DelaySwitch'
Thu Sep 28 2017 16:09:36 GMT-0400 (EDT) > [Thu Sep 28 2017 16:09:36 GMT-0400 (EDT)] ---
Thu Sep 28 2017 16:09:36 GMT-0400 (EDT) > [Thu Sep 28 2017 16:09:36 GMT-0400 (EDT)] Loaded plugin: homebridge-mi-aqara
Thu Sep 28 2017 16:09:36 GMT-0400 (EDT) > [Thu Sep 28 2017 16:09:36 GMT-0400 (EDT)] ---
Thu Sep 28 2017 16:09:37 GMT-0400 (EDT) > [Thu Sep 28 2017 16:09:37 GMT-0400 (EDT)] Loaded plugin: homebridge-people
Thu Sep 28 2017 16:09:37 GMT-0400 (EDT) > [Thu Sep 28 2017 16:09:37 GMT-0400 (EDT)] Registering platform 'homebridge-people.People'
(end excerpt of my log)

**As soon as I have the entry:**

		 {
        		"platform": "MiAqaraPlatform",
        		"sid": ["xxxxxxxxx"],
        		"password": ["xxxxxxxx"]
    		 },

**in my config.json, I am getting the following error:**

Thu Sep 28 2017 16:12:36 GMT-0400 (EDT) > [Thu Sep 28 2017 16:12:36 GMT-0400 (EDT)] Loaded plugin: homebridge-mi-aqara
/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:30
const iv = Buffer.from([0x17, 0x99, 0x6d, 0x09, 0x3d, 0x28, 0xdd, 0xb3, 0xba, 0x69, 0x5a, 0x2e, 0x6f, 0x58, 0x56, 0x2e]);
                  ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-aqara/MiAqaraPlatform.js:30:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Plugin.module.exports [as initializer] (/usr/local/lib/node_modules/homebridge-mi-aqara/index.js:8:5)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:150:14)

**Can somebody help? THANK YOU IN ADVANCE!!!**

**Comment by kevinlohk** [comment]
You are using the old version node. 
I check my Pi. node -v ,  it show v7.10.1 , it run the plugin without error.
I have another Pi , node -v ,  it show  v 4.3.2 , it will have the exact error that you show on above message.

**Comment by iCarl** [comment]
You are either using the wrong sid or password

**Comment by TheTherminator** [comment]
Thank you so much Guys! It was a problem with my password. It showed up in upper case on my phone, but I had to enter it in lower case.

**Comment by filippocobelli** [comment]
Hi
I would like to use my Aqara gateway with Homebridge but i can’t Find Mac id and password with mi app 4.3? 
I found i guide but was for the old version of the app...
Any help?
Thanks

**Comment by TheTherminator** [comment]
still works the same way, tap 5 times in the in Gateway/ About lower white area of the app and the hidden menu appears 





Best,
Stephan

On Dec 8, 2017, at 16:42, filippocobelli <notifications@github.com> wrote:

Hi
I would like to use my Aqara gateway with Homebridge but i can’t Find Mac id and password with mi app 4.3?
I found i guide but was for the old version of the app...
Any help?
Thanks
