### ISSUE TITLE
零火版双键开关问题

### ISSUE THREAD

**Issue by superszy** [YinHangCode/homebridge-mi-aqara#93]
如果把零火版双键开关的左键和右键同时加入homekit中的一个场景，当调用这个场景的时候会提示错误，但是实际上操控指令是被开关正常完成的。

如果是通过siri调用会提示“有一些设备没有响应”，如果是通过点击场景启用会提示“失败”。

已尝试设置"disableNoResponse": true和将开关设置为"syncValue": true，未能解决此问题。

谢谢。

**Comment by YinHangCode** [comment]
disableNoResponse只是两种展示失败的方式 本质上没啥区别 
-D启动 搞些日志看看

**Comment by superszy** [comment]
感谢回复，日志如下：

[11/7/2017, 10:03:47 AM] [MiAqaraPlatform] [DEBUG][Send]{"cmd":"write","model":"ctrl_ln2","sid":"158d00019cf810","data":"{\"channel_0\":\"on\", \"key\": \"4ac9fef230ff73ee3f95fedcc81c8d74\"}"}
[11/7/2017, 10:03:47 AM] [MiAqaraPlatform] [DEBUG][Send]{"cmd":"write","model":"ctrl_ln2","sid":"158d00019cf810","data":"{\"channel_1\":\"on\", \"key\": \"4ac9fef230ff73ee3f95fedcc81c8d74\"}"}
[11/7/2017, 10:03:47 AM] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"write_ack","model":"ctrl_ln2","sid":"158d00019cf810","short_id":50506,"data":"{\"voltage\":3600,\"channel_0\":\"off\",\"channel_1\":\"off\"}"}
[11/7/2017, 10:03:47 AM] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"write_ack","model":"ctrl_ln2","sid":"158d00019cf810","short_id":50506,"data":"{\"voltage\":3600,\"channel_0\":\"unknown\",\"channel_1\":\"off\"}"}
[11/7/2017, 10:03:47 AM] [MiAqaraPlatform] [ERROR]Error: {"voltage":3600,"channel_0":"unknown","channel_1":"off"}
[11/7/2017, 10:03:47 AM] [MiAqaraPlatform] [ERROR]Error: {"voltage":3600,"channel_0":"unknown","channel_1":"off"}
    at MiAqaraPlatform.parseMessage (/usr/lib/node_modules/homebridge-mi-aqara/index.js:302:26)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:548:8)
[11/7/2017, 10:03:47 AM] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"report","model":"ctrl_ln2","sid":"158d00019cf810","short_id":50506,"data":"{\"channel_0\":\"on\"}"}
[11/7/2017, 10:03:47 AM] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"report","model":"ctrl_ln2","sid":"158d00019cf810","short_id":50506,"data":"{\"channel_1\":\"on\"}"}

**Comment by YinHangCode** [comment]
明白了，现在的设计是收到的值是unknown的时候，认为设备并不是正常状态，返回错误，结果这个write_ack的回包里竟然有unknow。
下个版本我做个判断吧，判断一下含unknown的包 是否是真的无效。

**Comment by superszy** [comment]
那真的太好了，非常感谢。

**Comment by superszy** [comment]
问题已解决，谢谢~
