### ISSUE TITLE
Install and run problems

### ISSUE THREAD

**Issue by Shifter147** [YinHangCode/homebridge-mi-aqara#97]
Hello all! 

Im trying to get this plugin working. I installed it with this command: 
sudo npm install -g homebridge-mi-aqara

The only response i get from this : 
homebridge-mi-aqara@0.6.5 /usr/local/lib/node_modules/homebridge-mi-aqara

 I think it installed correctly, but i constantly get the following error:

pi@raspberrypi:~/.homebridge $ homebridge -D
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[Sat Nov 11 2017 09:04:41 GMT+0000 (UTC)] ====================
**[Sat Nov 11 2017 09:04:42 GMT+0000 (UTC)] ERROR LOADING PLUGIN homebridge-mi-aqara:**
[Sat Nov 11 2017 09:04:42 GMT+0000 (UTC)] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:141:14)
    at Array.forEach (native)
[Sat Nov 11 2017 09:04:42 GMT+0000 (UTC)] ====================
[Sat Nov 11 2017 09:04:45 GMT+0000 (UTC)] Loaded plugin: homebridge-sonoff-basic-espeasy
[Sat Nov 11 2017 09:04:45 GMT+0000 (UTC)] Registering accessory 'homebridge-sonoff-basic-espeasy.SonoffBasicESPEasy'
[Sat Nov 11 2017 09:04:45 GMT+0000 (UTC)] ---
[Sat Nov 11 2017 09:04:45 GMT+0000 (UTC)] Loaded config.json with 8 accessories and 1 platforms.
[Sat Nov 11 2017 09:04:45 GMT+0000 (UTC)] ---
[Sat Nov 11 2017 09:04:45 GMT+0000 (UTC)] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

**Error: The requested platform 'MiAqaraPlatform' was not registered by any plugin.**
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server.str.replace.Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:293:45)
    at Server.str.replace.Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)`

this is my config.json

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [

{
		 "accessory": "SonoffBasicESPEasy",
		 "name": "Sonoff01",
            	 "ip": "10.0.0.201"
	},

{
		"accessory": "SonoffBasicESPEasy",
      		"name": "Sonoff02",
      		"ip": "10.0.0.202"
	},

{
                 "accessory": "SonoffBasicESPEasy",
                 "name": "Sonoff03",
                 "ip": "10.0.0.203"
	},
{
                 "accessory": "SonoffBasicESPEasy",
                 "name": "Sonoff04",
                 "ip": "10.0.0.204"
	},

{
                 "accessory": "SonoffBasicESPEasy",
                 "name": "Sonoff05",
                 "ip": "10.0.0.205"
        },

{
                 "accessory": "SonoffBasicESPEasy",
                 "name": "Sonoff06",
                 "ip": "10.0.0.206"
        },

{
                 "accessory": "SonoffBasicESPEasy",
                 "name": "Sonoff07",
                 "ip": "10.0.0.207"
        },

{
                 "accessory": "SonoffBasicESPEasy",
                 "name": "Sonoff08",
                 "ip": "10.0.0.208"
        }

	],
    

    "platforms": [

{
        "platform": "MiAqaraPlatform",
        "gateways": {
            "6409802da3b3": "02i44k56zrgg578b"
        }
    }]

	
  
 
}

I hope someone can help me with this problem ! 

Thanks in advance! :)

**Comment by YinHangCode** [comment]
what's ur node version？

**Comment by Shifter147** [comment]
Version is 4.2.1 

pi@raspberrypi:~ $ node -v
v4.2.1

**Comment by YinHangCode** [comment]
try update to 7.9.x or later.

**Comment by Shifter147** [comment]
Thanks for the reply. Updated to 8.5.x and done a reinstall of Homebridge and plugin.  All works now !
